(async()=>{
 'use strict';const $=id=>document.getElementById(id),form=$('normEdit');let recipe;
 const format=v=>v==null?'—':v.toLocaleString('cs-CZ',{maximumFractionDigits:6});

 function dateLabel(value){return value?new Date(value+'T12:00:00').toLocaleDateString('cs-CZ'):'—'}
 function rotationNote(){const days={1:60,2:90,3:120}[form.elements.popularity.value];$('rotationNote').textContent=days?'Rotační interval: '+days+' dní od posledního použití.':'Rotační interval se vypočítá automaticky podle oblíbenosti.'}
 function renderHistory(){const dates=[...new Set([...(recipe.history||[]),recipe.lastServedAt].filter(Boolean))].sort(),gaps=dates.slice(1).map((d,i)=>(new Date(d)-new Date(dates[i]))/86400000),cut=new Date();cut.setFullYear(cut.getFullYear()-1);const average=gaps.length?Math.round(gaps.reduce((a,b)=>a+b,0)/gaps.length):null;const values=[dates.filter(d=>new Date(d+'T12:00:00')>=cut).length,average===null?'—':average+' dní',gaps.length?Math.min(...gaps)+' dní':'—',dates.length?'Historie zaznamenána':'Bez historie'];document.querySelectorAll('.history-summary b').forEach((b,i)=>b.textContent=values[i]);const host=document.querySelector('.history-summary').nextElementSibling;host.textContent=dates.length?dates.map(dateLabel).reverse().join(' · '):'Zatím nebylo zaznamenáno žádné použití.'}
 form.elements.popularity.addEventListener('change',rotationNote);
 function show(){
  const hero=document.querySelector('.detail-hero>span'),image=RecipeImports.imageHref(recipe);hero.replaceChildren();if(image){const img=document.createElement('img');img.src=new URL(image,document.baseURI);img.alt=recipe.name+' – AI ilustrace';img.title='AI ilustrace – návrh servírování';hero.append(img)}else{hero.textContent='🍽️'}
  $('normHeader').textContent=(['needs-completion','needs-review'].includes(recipe.completionStatus)?'K doplnění · ':'')+recipe.servings+' porcí';
  $('normDescription').textContent=recipe.description||'Popis zatím nebyl doplněn.';$('normPortions').textContent=recipe.servings;
  $('normTags').replaceChildren();for(const value of [...recipe.mealTypes,recipe.season.availability,recipe.meatType].filter(Boolean)){const tag=document.createElement('span');tag.textContent=value;$('normTags').append(tag)}
  $('normClassification').replaceChildren();for(const [label,value] of [['Sezóna',recipe.season.availability||'—'],['Doporučeno',recipe.season.recommendedDisplay||'—'],['Měsíce',recipe.season.months||'—'],['Oblíbenost',recipe.popularity||'Neurčena'],['Rotace',recipe.rotationDays?recipe.rotationDays+' dní':'Čeká na nastavení'],['Poslední použití',dateLabel(recipe.lastServedAt)],['Další rotace',recipe.lastServedAt&&recipe.rotationDays?dateLabel(new Date(new Date(recipe.lastServedAt+'T12:00:00').getTime()+recipe.rotationDays*86400000).toISOString().slice(0,10)):'—'],['Cena porce',recipe.pricePerServingCzk==null?'—':recipe.pricePerServingCzk.toLocaleString('cs-CZ',{minimumFractionDigits:2,maximumFractionDigits:2})+' Kč']]){const p=document.createElement('p'),span=document.createElement('span'),b=document.createElement('b');span.textContent=label;b.textContent=value;p.append(span,b);$('normClassification').append(p)}
  document.title=recipe.name;$('normName').textContent=recipe.name;$('normSource').textContent=`Zdroj: ${recipe.sourceFile} · Diety: ${recipe.sourceVariant||'neuvedeny'} · importovaná norma`;
  $('normServings').textContent=`Základ normy: ${recipe.servings} porcí. Množství v kusech nebyla odhadem převedena na gramy.`;
  $('normIngredients').replaceChildren();for(const i of recipe.ingredients){const row=document.createElement('div');row.className='ingredient-row';const name=document.createElement('span'),amount=document.createElement('b');name.textContent=i.name+(i.needsClarification?' · ⚠ upřesnit':'');amount.textContent=format(i.amount)+' '+i.unit;const detail=document.createElement('small');detail.style.cssText='display:block;font-weight:400;color:#64748a';detail.textContent=i.perServing?'Na porci: '+i.perServing:i.unit==='ks'?'Upřesnit balení':'';amount.append(detail);row.append(name,amount);$('normIngredients').append(row)}
  $('normWarnings').replaceChildren();for(const w of recipe.importWarnings){const li=document.createElement('li');li.textContent=w;$('normWarnings').append(li)}
  $('normNote').textContent=recipe.planningNote;$('normReview').textContent=recipe.nutritionReview;$('normNutrition').replaceChildren();
  const fields=[['energyKj','Energie','kJ'],['energyKcalApprox','Energie (přepočet)','kcal'],['proteinG','Bílkoviny','g'],['fatG','Tuky','g'],['carbohydratesG','Sacharidy','g'],['fiberG','Vláknina','g'],['calciumMg','Vápník','mg'],['ironMg','Železo','mg'],['vitaminAUg','Vitamín A','µg'],['vitaminB1Mg','Vitamín B1','mg'],['vitaminB2Mg','Vitamín B2','mg'],['vitaminCMg','Vitamín C','mg']];
  for(const [k,label,unit] of fields){const p=document.createElement('p'),s=document.createElement('span'),b=document.createElement('b');s.textContent=label;b.textContent=format(recipe.nutritionPerServing[k])+(recipe.nutritionPerServing[k]==null?'':' '+unit);p.append(s,b);$('normNutrition').append(p)}
  form.elements.name.value=recipe.name;form.elements.description.value=recipe.description;form.elements.price.value=recipe.pricePerServingCzk??'';form.elements.popularity.value=recipe.popularity??'';form.elements.planningNote.value=recipe.planningNote;
  for(const name of ['servings','meatType','sideDish','preparationType','status','lastServedAt'])form.elements[name].value=recipe[name]??'';
  form.elements.alternativeNames.value=recipe.alternativeNames.join(', ');form.elements.availability.value=recipe.season.availability||'';form.elements.recommended.value=recipe.season.recommendedDisplay||'';form.elements.months.value=recipe.season.months||'';
  for(const name of ['meatType','preparationType','availability','recommended']){const select=form.elements[name],value=name==='availability'?recipe.season.availability:name==='recommended'?recipe.season.recommendedDisplay:recipe[name];if(value&&!Array.from(select.options).some(o=>o.value===value))select.add(new Option(value,value));select.value=value||''}
  rotationNote();renderHistory();
  $('normMeals').replaceChildren();for(const meal of ['Snídaně','Oběd','Svačina','Večeře','Polévka','Příloha']){const l=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='meal';input.value=meal;input.checked=recipe.mealTypes.includes(meal);l.append(input,document.createTextNode(meal));$('normMeals').append(l)}
 }
 try{await RecipeImports.ready;recipe=RecipeImports.list().find(r=>r.id===(new URLSearchParams(location.search).get('id')||document.body.dataset.recipeId));if(!recipe)throw Error('Norma nebyla nalezena v katalogu. Obnovte její zálohu na stránce Import.');show();$('editButton').disabled=false}catch(e){$('normName').textContent=e.message;form.hidden=true;return;}
 $('editButton').addEventListener('click',()=>{show();$('normEditStatus').textContent='';$('editDialog').showModal()});for(const id of ['closeEdit','cancelEdit'])$(id).addEventListener('click',()=>$('editDialog').close());
 form.addEventListener('submit',async e=>{e.preventDefault();try{const portions=Number(form.elements.servings.value);const ingredients=portions===recipe.servings?recipe.ingredients:recipe.ingredients.map(i=>({...i,perServing:i.unit==='ks'?i.perServing:i.amount==null?null:(i.amount*(i.unit==='kg'||i.unit==='l'?1000:1)/portions).toLocaleString('cs-CZ',{maximumFractionDigits:6})+' '+(i.unit==='kg'?'g':i.unit==='l'?'ml':i.unit)}));recipe=await RecipeImports.update(recipe.id,{ingredients,alternativeNames:form.elements.alternativeNames.value.split(',').map(v=>v.trim()).filter(Boolean),servings:Number(form.elements.servings.value),meatType:form.elements.meatType.value,sideDish:form.elements.sideDish.value.trim(),preparationType:form.elements.preparationType.value,status:form.elements.status.value,lastServedAt:form.elements.lastServedAt.value||null,season:{...recipe.season,availability:form.elements.availability.value,recommendedDisplay:form.elements.recommended.value,recommended:form.elements.recommended.value.split('–').filter(Boolean),months:form.elements.months.value.trim()},name:form.elements.name.value.trim(),description:form.elements.description.value,pricePerServingCzk:form.elements.price.value===''?null:Number(form.elements.price.value),popularity:Number(form.elements.popularity.value)||null,planningNote:form.elements.planningNote.value,mealTypes:Array.from(form.querySelectorAll('[name=meal]:checked')).map(i=>i.value)});show();$('editDialog').close();$('normSaveStatus').textContent='Změny uloženy. '+RecipeImports.diskStatus()}catch(err){$('normEditStatus').textContent='Změny se neuložily: '+err.message}});
})();

