const KEY='receptar:zapecene-brambory-s-kurecim-masem-a-besamelem',defaults={name:'Zapečené brambory s kuřecím masem a bešamelem',alternativeNames:['Zapečené brambory s kuřetem','Kuřecí brambory s bešamelem'],history:[],lastServedAt:null};let recipe=load(),rows=[];
function load(){let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}return{...defaults,...saved,history:saved.history||[]}}
const norm=value=>(value||'').toLocaleLowerCase('cs').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim(),format=value=>new Intl.DateTimeFormat('cs-CZ').format(new Date(`${value}T12:00:00`));
function dateOf(line){const iso=line.match(/\b(20\d{2})-(\d{1,2})-(\d{1,2})\b/);if(iso)return`${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`;const cz=line.match(/\b(\d{1,2})\.\s*(\d{1,2})\.\s*(20\d{2})\b/);return cz?`${cz[3]}-${cz[2].padStart(2,'0')}-${cz[1].padStart(2,'0')}`:null}
function nameOf(line){return line.replace(/\b20\d{2}-\d{1,2}-\d{1,2}\b/,'').replace(/\b\d{1,2}\.\s*\d{1,2}\.\s*20\d{2}\b/,'').replace(/^[\s;|,\-–]+/,'').trim()}
function matches(name){const candidate=norm(name),aliases=[recipe.name,...(recipe.alternativeNames||[])].map(norm);if(aliases.some(alias=>candidate.includes(alias)||alias.includes(candidate)))return true;const words=new Set(candidate.split(' ').filter(word=>word.length>3));return aliases.some(alias=>{const other=new Set(alias.split(' ').filter(word=>word.length>3)),common=[...words].filter(word=>other.has(word)).length;return common>=2&&common/Math.max(words.size,other.size)>=.4})}
function analyze(){rows=document.querySelector('#menuText').value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean).map((line,id)=>{const name=nameOf(line);return{id,name,date:dateOf(line),matched:matches(name)}});const found=rows.filter(row=>row.matched).length;document.querySelector('#importSummary').innerHTML=`<b>Rozpoznáno ${found} z ${rows.length} řádků</b><span>${rows.length-found} neznámých jídel zůstává ke kontrole.</span>`;document.querySelector('#matchedMeals').innerHTML=rows.map(row=>`<div class="match-row ${row.matched?'matched':'unmatched'}"><span>${row.matched?'✓':'?'}</span><div><b>${row.name}</b><small>${row.date?format(row.date):'Chybí datum'} · ${row.matched?'Přiřazeno: '+recipe.name:'Nenalezeno v databázi'}</small></div>${row.matched&&row.date?`<input type="checkbox" checked data-row="${row.id}">`:''}</div>`).join('');document.querySelector('#importResults').hidden=false}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
document.querySelector('#menuFile').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{document.querySelector('#menuText').value=reader.result;analyze()};reader.readAsText(file,'utf-8')});document.querySelector('#analyzeMenu').addEventListener('click',analyze);document.querySelector('#saveImport').addEventListener('click',()=>{const selected=[...document.querySelectorAll('[data-row]:checked')].map(input=>rows[Number(input.dataset.row)]).filter(row=>row?.matched&&row.date);if(!selected.length){toast('Není vybráno žádné rozpoznané jídlo s datem.');return}const history=new Set(recipe.history||[]);selected.forEach(row=>history.add(row.date));recipe.history=[...history].sort();recipe.lastServedAt=recipe.history.at(-1);localStorage.setItem(KEY,JSON.stringify(recipe));toast(`Uloženo použití: ${selected.length}`)});
