(()=>{
 'use strict';
 const $=id=>document.getElementById(id),today=new Date().toISOString().slice(0,10),mealOrder=['Snídaně','Přesnídávka','Oběd','Polévka','Svačina','Večeře','Příloha'];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dateLabel=value=>new Intl.DateTimeFormat('cs-CZ',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(value+'T12:00:00'));
 const shortDate=value=>new Intl.DateTimeFormat('cs-CZ').format(new Date(value+'T12:00:00'));
 let imports=[],selected='';
 function period(item){if(item.from<=today&&item.to>=today)return'current';if(item.from>today)return'future';return'past'}
 async function staticCatalog(){const builtins=await fetch('builtin-recipes.json',{cache:'no-cache'}).then(r=>r.json()),index=await fetch('imported-index.json',{cache:'no-cache'}).then(r=>r.json()),sources=[...builtins.map(x=>({id:x.id,file:`Recepty/${x.id}/${x.id}.json`})),...(index.recipes||[])];return Promise.all(sources.map(async x=>{const response=await fetch(x.file,{cache:'no-cache'});if(!response.ok)return null;const recipe=await response.json();return{id:x.id,name:recipe.name,menuHistory:recipe.menuHistory||[]}})).then(x=>x.filter(Boolean))}
 async function load(){let recipes,registry=[];try{const response=await fetch('__menu_import',{cache:'no-store'}),type=response.headers.get('content-type')||'';if(!response.ok||!type.includes('application/json'))throw Error();const data=await response.json();recipes=data.recipes;registry=data.imports||[]}catch{recipes=await staticCatalog();try{const stored=JSON.parse(localStorage.getItem('receptar:menu-history:v1')||'null');if(stored?.version===1){registry=stored.imports||[];for(const event of stored.events||[]){const recipe=recipes.find(x=>x.id===event.recipeId);if(recipe)(recipe.menuHistory||(recipe.menuHistory=[])).push(event)}}}catch{}}
  const groups=new Map();for(const recipe of recipes)for(const event of recipe.menuHistory||[]){const key=event.importId||event.sourceFile||'starší-import';if(!groups.has(key))groups.set(key,{id:key,sourceFile:event.sourceFile||'Starší import',events:[]});groups.get(key).events.push({...event,recipeId:recipe.id,recipeName:recipe.name,confirmed:true})}
  for(const meta of registry){const group=groups.get(meta.id)||{id:meta.id,sourceFile:meta.sourceFile,events:[]};group.sourceFile=meta.sourceFile||group.sourceFile;groups.set(meta.id,group)}
  let draft;try{draft=JSON.parse(localStorage.getItem('receptar:menu-import-draft:v1')||'null')}catch{}if(draft?.version===1&&Array.isArray(draft.rows)){let group=draft.importId?groups.get(draft.importId):null;if(!group)group=[...groups.values()].find(x=>x.sourceFile===draft.fileName);if(!group){const id=draft.importId||`draft:${draft.fileName||'rozpracovany'}`;group={id,sourceFile:draft.fileName||'Rozpracovaný jídelníček',events:[]};groups.set(id,group)}const existing=new Set(group.events.map(x=>`${x.date}|${x.meal}|${String(x.originalName).toLocaleLowerCase('cs-CZ')}`));for(const row of draft.rows){const recipe=recipes.find(x=>x.id===row.recipeId);for(const event of row.occurrences||[]){const signature=`${event.date}|${event.meal}|${String(event.originalName).toLocaleLowerCase('cs-CZ')}`;if(existing.has(signature))continue;existing.add(signature);group.events.push({...event,recipeId:row.recipeId||'',recipeName:recipe?.name||'',confirmed:false})}}}
  imports=[...groups.values()].map(item=>{const dates=item.events.map(x=>x.date).filter(Boolean).sort();return{...item,from:dates[0]||'',to:dates.at(-1)||'',pending:item.events.filter(x=>!x.confirmed).length}}).filter(x=>x.events.length).sort((a,b)=>b.from.localeCompare(a.from));selected=imports[0]?.id||'';renderFilters();render()}
 function renderFilters(){const filter=$('importFilter'),current=filter.value||selected;filter.innerHTML=imports.map(x=>`<option value="${esc(x.id)}">${esc(x.sourceFile)} · ${shortDate(x.from)}–${shortDate(x.to)}</option>`).join('');selected=imports.some(x=>x.id===current)?current:(imports[0]?.id||'');filter.value=selected}
 function render(){const wanted=$('periodFilter').value,visible=imports.filter(x=>wanted==='all'||period(x)===wanted);$('menuCount').textContent=`${visible.length} jídelníčků`;$('menusOverview').innerHTML=visible.map(x=>`<button class="menu-import-card ${x.id===selected?'active':''}" data-menu-id="${esc(x.id)}"><b>${esc(x.sourceFile)}</b><small>${shortDate(x.from)} až ${shortDate(x.to)} · ${x.events.length} položek${x.pending?` · ${x.pending} nepotvrzených`:''}</small></button>`).join('');if(!visible.some(x=>x.id===selected))selected=visible[0]?.id||'';const item=imports.find(x=>x.id===selected);if(!item){$('menuDays').innerHTML='<div class="menus-empty"><b>Žádný jídelníček v tomto období</b><span>Změňte filtr nebo nejprve jídelníček naimportujte.</span></div>';return}const days=new Map();for(const event of item.events){if(!days.has(event.date))days.set(event.date,[]);days.get(event.date).push(event)}$('menuDays').innerHTML=[...days].sort(([a],[b])=>a.localeCompare(b)).map(([date,events])=>{const state=date===today?'today':date>today?'future':'past',label=date===today?'Dnes':date>today?'Budoucí':'Minulé',meals=new Map();for(const e of events){if(!meals.has(e.meal))meals.set(e.meal,[]);meals.get(e.meal).push(e)}const blocks=[...meals].sort(([a],[b])=>mealOrder.indexOf(a)-mealOrder.indexOf(b)).map(([meal,items])=>`<section class="meal-block"><h3>${esc(meal)}</h3><ul>${items.map(e=>`<li class="${e.confirmed?'':'pending-menu-item'}"><b>${esc(e.originalName||e.recipeName)}</b>${e.confirmed?'':'<span class="confirm-badge">Nepotvrzeno</span>'}${e.recipeName&&e.recipeName!==e.originalName?`<small>Recept: ${esc(e.recipeName)}</small>`:''}${e.dietCode?`<small>Dieta: ${esc(e.dietCode)}</small>`:''}</li>`).join('')}</ul></section>`).join('');return`<article class="menu-day ${state}"><div class="day-heading"><h2>${esc(dateLabel(date))}</h2><span>${label}</span></div><div class="day-meals">${blocks}</div></article>`}).join('');$('menusStatus').textContent=`Zobrazen kompletní jídelníček ${item.sourceFile}: ${shortDate(item.from)} až ${shortDate(item.to)}. ${item.pending?item.pending+' položek čeká na potvrzení.':'Všechny položky jsou potvrzené.'}`}
 $('periodFilter').addEventListener('change',render);$('importFilter').addEventListener('change',e=>{selected=e.target.value;render()});$('menusOverview').addEventListener('click',e=>{const button=e.target.closest('[data-menu-id]');if(!button)return;selected=button.dataset.menuId;$('importFilter').value=selected;render()});$('todayLabel').textContent=dateLabel(today);load().catch(error=>{$('menusStatus').textContent='Jídelníčky se nepodařilo načíst: '+error.message;$('menuDays').innerHTML='<div class="menus-empty"><b>Data nejsou dostupná</b><span>Zkontrolujte připojení nebo místní server.</span></div>'});
})();
